name: Calendar Version
author: Eric Marshall
runs:
  using: node16
  main: dist/index.js
description: Calendar based versioning
branding:
  color: blue
  icon: calendar
inputs:
  token:
    description: The github action token
    required: true
  create_tag:
    description: Whether to create the generated tag with the new version
    required: false
    default: "true"
  tag_prefix:
    description: "A prefix for the generated version tag"
    required: false
    default: "v"
  release_months:
    description: A comma/newline separated list of months at which the minor version segment should be incremented
    required: false
    default: ""
outputs:
  old_tag:
    description: The base tag used to generate the new version/tag
  old_version:
    description: The base version parsed from old_tag
  new_tag:
    description: The generated tag
  new_version:
    description: The generated version
